[package]
name = "dockerbackup"
version = "3.0.0"
edition = "2021"
authors = ["Radek"]
license = "MIT OR Apache-2.0"
description = "A simple Docker backup and restore tool"
readme = "README.md"
homepage = "https://github.com/radek00/dockerbackup"
repository = "https://github.com/radek00/dockerbackup"
keywords = ["cli", "backup", "docker"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
reqwest = { version = "0.13", features = ["blocking", "json"] }
clap = "4.6.4"
ctrlc = "3.5.2"
crossterm = "0.29.0"
